<template>
	<div><MobileRecordList :data="tableData.data" row-key="recordId" data-mobile-view="anchor-list"><template #desktop><el-table :data="tableData.data" @selection-change="selection=$event">
		<el-table-column type="selection" width="48" :selectable="(row:any)=>row.recordType==='PROFILE'"/><el-table-column type="index" label="序号" width="60"/>
		<el-table-column label="主播" min-width="170"><template #default="{row}"><div class="anchor-identity"><el-avatar :src="row.avatar?getUpFileUrl(row.avatar):''">{{row.nickname?.slice(0,1)||'-'}}</el-avatar><span>{{row.nickname||'-'}}</span></div></template></el-table-column>
		<el-table-column label="主播ID" min-width="135"><template #default="{row}"><div v-for="b in row.bindings" :key="b.id">{{b.anchorId}}</div><span v-if="!row.bindings?.length">待绑定</span></template></el-table-column>
		<el-table-column label="所属厅" min-width="120"><template #default="{row}"><div v-for="b in row.bindings" :key="b.id">{{b.hallName||b.hallId}}</div><span v-if="!row.bindings?.length">-</span></template></el-table-column>
		<el-table-column label="开播情况" min-width="145"><template #default="{row}"><el-tag :type="liveStatusTag(row.vvCurrentLiveStatus)">{{row.vvCurrentLiveStatus||'-'}}</el-tag><div class="subtext">{{row.vvRecentDevelopments||(`${row.vvNotLiveDays||0}天未开播`)}}</div></template></el-table-column>
		<el-table-column label="签约" min-width="170"><template #default="{row}"><el-tag type="info">{{row.vvAnchorTypeName||'-'}}</el-tag><div class="subtext">到期：{{dateOnly(row.vvSignExpiredTime)}}</div></template></el-table-column>
		<el-table-column label="魅力&粉丝数" min-width="135"><template #default="{row}"><div>魅力 {{row.vvCharmLevel??0}}</div><div class="subtext">粉丝 {{row.vvFansCount??0}}</div></template></el-table-column>
		<el-table-column label="账号状态" min-width="125"><template #default="{row}"><el-tag :type="forbidStatusTag(row.vvForbidStatus)">{{row.vvForbidStatusName||'-'}}</el-tag></template></el-table-column>
		<el-table-column label="微信群" min-width="180"><template #default="{row}"><div v-for="g in row.groups" :key="g.groupId"><el-tag :type="g.isPresent?'success':'info'" size="small">{{g.groupName}}·{{g.groupNickname||'-'}}</el-tag></div><span v-if="!row.groups?.length">-</span></template></el-table-column>
		<el-table-column label="绑定" width="90"><template #default="{row}"><el-tag :type="row.bindingStatus==='BOUND'?'success':'warning'">{{bindingText[row.bindingStatus]||row.bindingStatus}}</el-tag></template></el-table-column>
		<el-table-column label="资料" width="90"><template #default="{row}">{{row.profileCompleteness==='COMPLETE'?'已完善':'待完善'}}</template></el-table-column>
		<el-table-column label="操作" width="290" fixed="right"><template #default="{row}"><el-button text type="primary" @click="openDetail(row)">详情</el-button><el-button text type="primary" @click="openEditDialog(row)">编辑</el-button><el-button v-if="hasBankCardOwner(row)" text type="primary" @click="openBankCardDialog(row)">工资卡</el-button><el-button v-if="row.recordType==='PROFILE'&&row.recordState==='ACTIVE'" v-auth="'api/v1/system/anchor/profile/batchDelete'" text type="danger" @click="deleteRow(row)">删除</el-button><el-button v-if="row.recordType==='LEGACY_ANCHOR'" v-auth="'api/v1/system/anchor/delete'" text type="danger" @click="deleteRow(row)">删除</el-button><el-button v-if="row.recordType==='PROFILE'&&row.recordState==='ACTIVE'" v-auth="'api/v1/system/anchor/profile/batchIgnore'" text type="warning" @click="runBatch('IGNORE',[row.profileId])">忽略</el-button><el-button v-if="row.recordState==='IGNORED'" v-auth="'api/v1/system/anchor/profile/batchCancelIgnore'" text @click="runBatch('CANCEL_IGNORE',[row.profileId])">取消忽略</el-button></template></el-table-column>
	</el-table></template><template #default="{ row }">
		<div class="mobile-record-card__header"><div class="anchor-mobile-identity"><el-avatar class="anchor-mobile-avatar" :src="row.avatar?getUpFileUrl(row.avatar):''">{{ row.nickname?.slice(0,1)||'-' }}</el-avatar><h3 class="mobile-record-card__title">{{ row.nickname }}</h3></div></div>
		<dl class="mobile-record-card__fields"><div><dt>主播ID</dt><dd>{{ row.bindings?.map((item:any)=>item.anchorId).join('、')||'待绑定' }}</dd></div><div><dt>所属厅</dt><dd>{{ row.bindings?.map((item:any)=>item.hallName||item.hallId).join('、')||'-' }}</dd></div><div><dt>开播</dt><dd>{{row.vvCurrentLiveStatus||'-'}}</dd></div><div><dt>魅力&粉丝数</dt><dd>{{row.vvCharmLevel??0}} / {{row.vvFansCount??0}}</dd></div><div><dt>账号</dt><dd>{{row.vvForbidStatusName||'-'}}</dd></div><div><dt>微信群</dt><dd>{{ row.groups?.map((item:any)=>item.groupName).join('、')||'-' }}</dd></div></dl>
		<div class="mobile-record-card__actions"><el-button type="primary" @click="openDetail(row)">详情</el-button><el-button @click="openEditDialog(row)">编辑</el-button><el-button v-if="hasBankCardOwner(row)" @click="openBankCardDialog(row)">工资卡</el-button><el-dropdown><el-button>更多</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item v-if="row.recordType==='PROFILE'&&row.recordState==='ACTIVE'"><el-button v-auth="'api/v1/system/anchor/profile/batchDelete'" text type="danger" @click="deleteRow(row)">删除</el-button></el-dropdown-item><el-dropdown-item v-if="row.recordType==='LEGACY_ANCHOR'"><el-button v-auth="'api/v1/system/anchor/delete'" text type="danger" @click="deleteRow(row)">删除</el-button></el-dropdown-item><el-dropdown-item v-if="row.recordType==='PROFILE'&&row.recordState==='ACTIVE'"><el-button v-auth="'api/v1/system/anchor/profile/batchIgnore'" text @click="runBatch('IGNORE',[row.profileId])">忽略</el-button></el-dropdown-item><el-dropdown-item v-if="row.recordState==='IGNORED'"><el-button v-auth="'api/v1/system/anchor/profile/batchCancelIgnore'" text @click="runBatch('CANCEL_IGNORE',[row.profileId])">取消忽略</el-button></el-dropdown-item></el-dropdown-menu></template></el-dropdown></div>
	</template></MobileRecordList>
	<pagination v-show="tableData.total>0" :total="tableData.total" v-model:page="tableData.param.pageNum" v-model:limit="tableData.param.pageSize" @pagination="loadList"/>
	<EditAnchor ref="editAnchorRef" :hall-options="hallOptions" :platform-options="platformOptions" @success="loadList"/><BankCardDialog ref="bankCardDialogRef" @success="loadList"/>
	<el-drawer v-model="detailVisible" title="主播详情" size="520px"><template v-if="detailRow"><div class="detail-identity"><el-avatar :size="64" :src="detailRow.avatar?getUpFileUrl(detailRow.avatar):''">{{detailRow.nickname?.slice(0,1)||'-'}}</el-avatar><div><h3>{{detailRow.nickname||'-'}}</h3><p>{{detailRow.bindings?.map((item:any)=>item.anchorId).join('、')||'待绑定'}}</p></div></div><el-descriptions :column="2" border><el-descriptions-item label="所属厅">{{detailRow.bindings?.map((item:any)=>item.hallName||item.hallId).join('、')||'-'}}</el-descriptions-item><el-descriptions-item label="平台">{{detailRow.bindings?.map((item:any)=>item.platformName||item.platformCode).join('、')||'-'}}</el-descriptions-item><el-descriptions-item label="管理员">{{detailRow.vvVpUserName||'-'}}<span v-if="detailRow.vvVpUserId">（{{detailRow.vvVpUserId}}）</span></el-descriptions-item><el-descriptions-item label="组长">{{detailRow.vvLeaderUserName||'-'}}<span v-if="detailRow.vvLeaderUserId">（{{detailRow.vvLeaderUserId}}）</span></el-descriptions-item><el-descriptions-item label="签约类型">{{detailRow.vvAnchorTypeName||'-'}}</el-descriptions-item><el-descriptions-item label="签约时间">{{dateOnly(detailRow.vvContractTime)}} 至 {{dateOnly(detailRow.vvSignExpiredTime)}}</el-descriptions-item><el-descriptions-item label="用户等级">{{detailRow.vvUserLevel||'-'}}</el-descriptions-item><el-descriptions-item label="魅力等级">{{detailRow.vvCharmLevel??0}}</el-descriptions-item><el-descriptions-item label="直播等级">{{detailRow.vvLiveLevel??0}}</el-descriptions-item><el-descriptions-item label="粉丝数">{{detailRow.vvFansCount??0}}</el-descriptions-item><el-descriptions-item label="开播状态">{{detailRow.vvCurrentLiveStatus||'-'}}</el-descriptions-item><el-descriptions-item label="最近开播">{{detailRow.vvRecentDevelopments||'-'}}</el-descriptions-item><el-descriptions-item label="账号状态">{{detailRow.vvForbidStatusName||'-'}}</el-descriptions-item><el-descriptions-item label="同步时间">{{detailRow.vvSyncedAt||'-'}}</el-descriptions-item><el-descriptions-item label="真实姓名">{{detailRow.realName||'-'}}</el-descriptions-item><el-descriptions-item label="手机号">{{detailRow.mobile||'-'}}</el-descriptions-item><el-descriptions-item label="备注" :span="2">{{detailRow.remark||'-'}}</el-descriptions-item></el-descriptions></template></el-drawer>
	</div>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref, toRefs, watch } from 'vue'; import { ElMessage,ElMessageBox } from 'element-plus';
import EditAnchor from './editAnchor.vue'; import BankCardDialog from './bankCardDialog.vue';
import { cancelIgnoreAnchorProfiles,deleteAnchorProfiles,deleteLegacyAnchor,getAnchorList,ignoreAnchorProfiles,previewAnchorBatch } from '/@/api/anchor'; import { getUpFileUrl } from '/@/utils/gfast';
defineOptions({name:'anchorList'}); const props=defineProps({query:{type:Object,default:()=>({})},hallOptions:{type:Array,default:()=>[]},platformOptions:{type:Array,default:()=>[]}});
const editAnchorRef=ref(); const bankCardDialogRef=ref(); const selection=ref<any[]>([]); const detailVisible=ref(false); const detailRow=ref<any>(); const bindingText:Record<string,string>={BOUND:'已绑定',PENDING:'待绑定',UNLINKED_WECHAT:'未关联微信'};
const state=reactive({tableData:{data:[] as any[],total:0,param:{pageNum:1,pageSize:10}}}); const {tableData}=toRefs(state);
const loadList=()=>getAnchorList({...state.tableData.param,...props.query}).then((res:any)=>{state.tableData.data=res.data.list??[];state.tableData.total=res.data.total??0;});
const openAddDialog=()=>editAnchorRef.value?.openDialog(); const openEditDialog=(row:any)=>editAnchorRef.value?.openDialog(row);
const openDetail=(row:any)=>{detailRow.value=row;detailVisible.value=true;};
const dateOnly=(value:string)=>value?value.slice(0,10):'-';
const liveStatusTag=(value:string)=>value==='开播中'?'success':'info';
const forbidStatusTag=(value:number)=>value===0?'success':value===1?'danger':'warning';
const hasBankCardOwner=(row:any)=>row.bindings?.some((binding:any)=>binding.anchorId&&binding.hallId);
const bankCardOwner=(row:any)=>({profileId:row.recordType==='PROFILE'?row.profileId:0,anchorInfoId:row.recordType==='LEGACY_ANCHOR'?row.id:0,nickname:row.nickname});
const openBankCardDialog=(row:any)=>bankCardDialogRef.value?.openDialog(bankCardOwner(row));
const deleteRow=async(row:any)=>{if(row.recordType==='PROFILE'){await runBatch('DELETE',[row.profileId]);return;}await ElMessageBox.confirm(`确认删除历史主播 ${row.nickname}？存在工资卡时将拒绝删除；已有麦序历史会保留。`,'删除确认',{type:'warning'});await deleteLegacyAnchor(row.id);ElMessage.success('删除成功');loadList();};
const runBatch=async(action:string,ids?:number[])=>{const profileIds=ids??selection.value.map(r=>r.profileId);const filter=profileIds.length?{}:{...props.query};const narrowed=filter.nickname||filter.anchorId||filter.platformCode||filter.hallId||filter.groupId||filter.bindingStatus||filter.presenceStatus||filter.completeness||filter.vvCurrentLiveStatus||filter.vvForbidStatus||(filter.recordState&&filter.recordState!=='ACTIVE');if(!profileIds.length&&!narrowed){ElMessage.warning('请先勾选成员或设置昵称、主播ID、平台、厅、群或状态筛选');return;}const preview:any=await previewAnchorBatch({action,profileIds,filter});const p=preview.data;await ElMessageBox.confirm(`命中 ${p.matched}，可操作 ${p.actionable}，受阻 ${p.blocked}${p.blockedReason?'：'+p.blockedReason:''}`,'批量操作确认',{type:'warning'});const requests:Record<string,any>={DELETE:deleteAnchorProfiles,IGNORE:ignoreAnchorProfiles,CANCEL_IGNORE:cancelIgnoreAnchorProfiles};const result:any=await requests[action]({profileIds,filter});ElMessage.success(`成功 ${result.data.success}，受阻 ${result.data.blocked}`);loadList();};
watch(()=>props.query,()=>{state.tableData.param.pageNum=1;loadList();},{deep:true}); onMounted(loadList); defineExpose({loadList,openAddDialog,runBatch});
</script>

<style scoped>
.anchor-mobile-identity { display: flex; align-items: center; min-width: 0; gap: 12px; }
.anchor-identity,.detail-identity { display:flex;align-items:center;gap:10px; }
.detail-identity { margin-bottom:18px; }
.detail-identity h3,.detail-identity p { margin:0; }
.subtext { margin-top:4px;color:var(--el-text-color-secondary);font-size:12px; }
</style>
